name: Convert TXT to SRS

on:
  workflow_dispatch:
  schedule:
    - cron: '5 1 * * *'

jobs:
  install-and-compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Sing-Box
      run: |
        bash <(curl -fsSL https://sing-box.app/deb-install.sh)

    - name: Download AdGuard DNS Filter
      run: |
        curl -o adblockdns.txt https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdns.txt

    - name: Convert AdGuard DNS Filter to megamori.srs
      run: |
        sing-box rule-set convert --type adguard --output megamori.srs adblockdns.txt

    - name: Commit and Push SRS file
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add megamori.srs  # 只添加 megamori.srs 文件
        git commit -m "Auto-update megamori.srs" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
